name: CD

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          install_only: true

      - name: Clean
        run: |
          rm -rf .cr-release-packages && mkdir -p .cr-release-packages
          rm -rf .cr-index && mkdir -p .cr-index
          rm -rf .vllm-helm && mkdir -p .vllm-helm

      - name: Copy vLLM chart
        run: |
          cp -r templates .vllm-helm/
          cp Chart.yaml .vllm-helm/
          cp values.yaml .vllm-helm/
          cp values.schema.json .vllm-helm/
          cp README.md .vllm-helm/

      - name: Package chart
        run: cr package .

      - name: Upload chart
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cr upload --owner ${{ github.repository_owner }} --git-repo vllm-helm \
            --generate-release-notes \
            -c "$(git rev-parse HEAD)"

      - name: Upload chart index
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cr index --owner ${{ github.repository_owner }} --git-repo vllm-helm --push
